### ISSUE TITLE
lid can be resized when its not on the container

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gas-properties#151]
**Test device**
Dell Laptop
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/386 and https://github.com/phetsims/QA/issues/388
Note that this is difficult if not impossible to reproduce without slowing down the sim, meaning that I don't think it needs to be solved unless the solution is trivial.
If you drag on the lid while it is blowing off, you can change its size.
**Steps to reproduce**
1. Add the query parameter speed=.1
2. Add a large number of particles and either heat or shrink volume until lid comes off.
3. As lid goes off screen, grab the handle and move it around

**Visuals**
https://drive.google.com/file/d/1EVp7B495XVQIv6BanL91yF9nhuU610OQ/view?usp=sharing

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Gas Properties‬
URL: https://phet-dev.colorado.edu/html/gas-properties/1.0.0-rc.1/phet/gas-properties_all_phet.html?speed=.1
Version: 1.0.0-rc.1 2019-07-29 20:25:10 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
Can be more obvious if you make the container bigger after lid blows off.
https://drive.google.com/file/d/1bVfF7GbAVe5feA2XD4wtQd645fd-Pu1x/view?usp=sharing

**Comment by KatieWoe** [comment]
Update: This is easier to do if you use the pause and step through functions

**Comment by pixelzoom** [comment]
This should be easy to fix.  Make the lid `pickable:false` when it's not on the container.

**Comment by pixelzoom** [comment]
Fixed in master and 1.0 branches. The lid is not interactive only when it is on the container.

@KatieWoe please verify in master.

**Comment by KatieWoe** [comment]
Can still happen in master, but harder.  Now, you must first move the container wall, then the lid.  Pausing makes this a bit easier to accomplish.
![stillcanhappenbutmuchharder](https://user-images.githubusercontent.com/41024075/62166353-c7233280-b2dd-11e9-8688-fc944912cee1.gif)

**Comment by pixelzoom** [comment]
OK, I'll investigate more tomorrow.

**Comment by pixelzoom** [comment]
Fixed in master and 1.0 branches.  Resizing the container will make the lid pickable only if the lid is on the container. 

@KatieWoe please verify in master.

**Comment by KatieWoe** [comment]
Does seem to be fixed in master.

**Comment by pixelzoom** [comment]
To be verified in 1.0.0-rc.2.

**Comment by KatieWoe** [comment]
looks good rc.2
